Curso de Capacitação em IA (2023)
[MCTI, SOFTEX, IFMA Monte Castelo]

# Atividade de Fixação
## Tópico: 3.1 - Numpy


### Instruções

1. Este notebook deve ser utilizado para fixação dos conceitos.
1. Abra este notebook no jupyter, jupyter lab, vscode (com extensões) ou no colab.  
1. Responda cada questão com seu código e execute. Verifique a saída, corrija se necessário, e execute novamente. 
1. Algumas questões admitem várias formas de resposta. Neste caso, adicione células com suas várias respostas. 



### Configurações

In [2]:
import numpy as np

## Questões

### Criação de ndarrays

1. Crie um ndarray de 5 itens a partir de números quaisquer (cada aluno deve utilizar numeros diferentes)

In [2]:
# Sua resposta aquisdadas
a = np.array([1,2,3,4,5])
a

2. Crie um ndarray de 5 numeros inteiros em um dado intervalo 

In [3]:
# Digite seu codigo aqui
a = np.array([1,2,3,4,5])
meu_array = np.array([[0,1],[2,3],[4,5]])
meu_array.shape

(3, 2)

3. Crie um ndarray com 100 números reais no mesmo intervalo da questão anterior 

In [13]:
# Digite seu codigo aqui
a = np.random.rand(100)
print(a)

[0.33633343 0.81539361 0.03755981 0.65399298 0.51730566 0.79477465
 0.71780422 0.28772701 0.04331901 0.30228954 0.02259891 0.1250689
 0.06537848 0.99818176 0.71905002 0.79829225 0.40421473 0.65402488
 0.58500813 0.19526217 0.7679264  0.29258412 0.45847047 0.48333559
 0.9728787  0.39383963 0.67522689 0.14521031 0.39979391 0.2862504
 0.32397863 0.82049957 0.03951761 0.7703979  0.09071777 0.27283164
 0.88972006 0.53727123 0.13329507 0.25176023 0.07257336 0.11675328
 0.38918061 0.29261486 0.64886538 0.96583456 0.54476549 0.50775746
 0.16777894 0.06523513 0.99198128 0.90010468 0.04920252 0.18248142
 0.15200246 0.51659408 0.41835336 0.15948693 0.44110755 0.77396935
 0.05901933 0.16615394 0.80610892 0.92332783 0.26983859 0.2563161
 0.65083203 0.82977698 0.02302415 0.53868668 0.37730028 0.26330551
 0.33009012 0.74583655 0.43850817 0.39614308 0.50631214 0.95493598
 0.87567735 0.17704425 0.85463847 0.39317928 0.57635888 0.50693048
 0.37599338 0.21574095 0.19827347 0.71980614 0.22064154 0.9371859

4. Crie uma matriz quadrada de dimensão maior que 4, onde a diagonal principal é formada por valores 3 

In [14]:
# Digite seu codigo aqui
matriz = np.zeros((5, 5))
np.fill_diagonal(matriz, 3)
print(matriz)


[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


### Fatiamento e indexação

5. Crie uma estrutura de duas dimensões com alguns poucos números, ex. 12. Selecione todos os números mas ignore as últimas duas linhae e considere apenas a ultima coluna. 

In [17]:
# Digite seu codigo aqui
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10,11,12]])

print(matriz[:2, -1])

[3 6]


6. Extraia todos os números que sejam maior (ou menor) que a media (ou mediana) dos valores que você escolheu

In [21]:
# Digite seu codigo aqui

media = np.mean(matriz)
print(media)
maiores_que_media = matriz[matriz < media]
print(maiores_que_media)

6.5
[1 2 3 4 5 6]


7. Substitua todos os números menores que a média do array por 0, preservando os valores do array original

In [5]:
# Digite seu codigo aqui
matriz_modificada = matriz.copy()
matriz_modificada[matriz < media] = 0


8. Crie um array numpy de tamanho 7x7 com valores aleatórios inteiros entre 1 e 100 (inclusive). Em seguida, encontre o valor máximo e o valor mínimo em cada linha do arr

In [27]:
# Digite seu código aqui
array = np.random.randint(1, 101, (7, 7))
maximos_por_linha = np.max(array, axis=1)
minimos_por_linha = np.min(array, axis=1)
print(array)
print(maximos_por_linha)
print(minimos_por_linha)

[[ 87  82  30   3  63  67  95]
 [ 86  25  72  77  74 100 100]
 [ 47  77  22  91  11  71  81]
 [ 49  86  91  86   3   5  65]
 [ 44  25  15   3  93  25  63]
 [ 19  94  84  20  10  87  61]
 [ 12  64  99  90   6  11  40]]
[ 95 100  91  91  93  94  99]
[ 3 25 11  3  3 10  6]


9. Crie um array numpy de tamanho 8x8 com valores aleatórios entre 0 e 1 (exclusive). Em seguida, crie um novo array onde todos os valores menores que 0.5 são substituídos por 0 e todos os valores maiores ou iguais a 0.5 são substituídos por 1.

In [34]:
# Digite seu código aqui
array_original = np.random.random((8, 8))
print(array_original)
array_modificado = np.where(array_original < 0.5, 0, 1)
print(array_modificado)

[[0.54599176 0.74910008 0.54448256 0.93928092 0.96768156 0.64153156
  0.17450143 0.34879942]
 [0.91725545 0.39970053 0.55487539 0.53586667 0.27848778 0.18852772
  0.73338346 0.18809905]
 [0.8026672  0.44452696 0.58904614 0.47637261 0.94702343 0.312947
  0.85725071 0.8320004 ]
 [0.82179219 0.6745795  0.45126561 0.39491502 0.0615499  0.9688481
  0.76536459 0.23735203]
 [0.46346969 0.08225052 0.20781874 0.40169618 0.28764428 0.71013153
  0.72754105 0.58494846]
 [0.72976395 0.19592816 0.32765672 0.83520908 0.01462261 0.81052903
  0.0053413  0.79741501]
 [0.70415579 0.50599149 0.78916145 0.42571787 0.65439885 0.86543976
  0.12747185 0.11944955]
 [0.66065803 0.99232427 0.30531766 0.92566577 0.1389489  0.27758037
  0.00106957 0.7906625 ]]
[[1 1 1 1 1 1 0 0]
 [1 0 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 1]
 [1 1 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]
 [1 0 0 1 0 1 0 1]
 [1 1 1 0 1 1 0 0]
 [1 1 0 1 0 0 0 1]]


### Mudança de Formato

10. De um exemplo onde um ndarray de 1D é transformado em 2D. Por exemplo, transformar um vetor 1D em uma matriz coluna ou matriz linha

11. Mostre como empilhar verticalmente dois ndarrays de 2 dimensões (matrizes) de dimensões compatíveis. Fique à vontade para mostra concatenação em qualquer um dos eixos 

In [38]:
# Digite seu codigo aqui

vetor_1d = np.array([1, 2, 3, 4, 5])

# Transforme em uma matriz coluna (2D)
matriz_coluna = vetor_1d[:, np.newaxis]

# Exiba o resultado
print("Vetor 1D:")
print(vetor_1d)
print("\nMatriz Coluna (2D):")
print(matriz_coluna)

Vetor 1D:
[1 2 3 4 5]

Matriz Coluna (2D):
[[1]
 [2]
 [3]
 [4]
 [5]]


**Nota:** stackoverflow.com/questions/33356442/when-should-i-use-hstack-vstack-vs-append-vs-concatenate-vs-column-stack

## Miscelânea

12. Como calcular media, desvio e mediana de um array?

In [39]:
# Digite seu codigo aqui
dados = np.array([1, 2, 3, 4, 5])

media = np.mean(dados)

desvio_padrao = np.std(dados)

mediana = np.median(dados)

print(media)
print(desvio_padrao)
print(mediana)

3.0
1.4142135623730951
3.0


13. Como normalizar os valores em um ndarray? 

** Nota**: *normalizar* é uma operação matemática que subtrai a média dos dados e divide pelo seu desvio padrão. 

In [40]:
# Digite seu codigo aqui
dados = np.array([1, 2, 3, 4, 5])

# Calcula a média e o desvio padrão dos dados
media = np.mean(dados)
desvio_padrao = np.std(dados)

# Normaliza os dados aplicando a fórmula z-score
dados_normalizados = (dados - media) / desvio_padrao

print(dados_normalizados)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


14. Calcular correlação entre dois vetores

In [44]:
# Digite seu codigo aqui
vetor1 = np.array([1, 2, 3, 4, 5])
vetor2 = np.array([1, 3, 2, 4, 5])

# Calcule a matriz de correlação entre os dois vetores
matriz_correlacao = np.corrcoef(vetor1, vetor2)

print(matriz_correlacao)
# A correlação entre os dois vetores está na posição (0, 1) ou (1, 0) da matriz
correlacao = matriz_correlacao[0, 1]

# Exiba a correlação
print("Correlação entre vetor1 e vetor2:", correlacao)

[[1.  0.9]
 [0.9 1. ]]
Correlação entre vetor1 e vetor2: 0.8999999999999998


15. Crie uma matriz 5 x5 com vários valores repetidos entre 0 e 9. Em seguida aprsente a quantidade de ocorrencias de cada valor unicos em um ndarray

In [48]:
# Digite seu codigo aqui
matriz = np.random.randint(0, 10, (5, 5))

# Exiba a matriz
print("Matriz:")
print(matriz)

# Conte a quantidade de ocorrências de cada valor único
valores_unicos, contagens = np.unique(matriz, return_counts=True)

# Crie um ndarray com as contagens correspondentes a cada valor único
ocorrencias = np.column_stack((valores_unicos, contagens))

# Exiba as ocorrências de cada valor único
print("\nOcorrências de Valores Únicos:")
print(ocorrencias)

Matriz:
[[4 5 7 7 6]
 [8 6 0 9 1]
 [1 8 6 2 9]
 [8 1 5 1 2]
 [3 8 5 9 7]]

Ocorrências de Valores Únicos:
[[0 1]
 [1 4]
 [2 2]
 [3 1]
 [4 1]
 [5 3]
 [6 3]
 [7 3]
 [8 4]
 [9 3]]


# Referências

Se você quiser, veja mais exercícios no link abaixo. Atente para o fato de que algumas das respostas neste link não valem mais para a versão atual do numpy. 

https://www.machinelearningplus.com/python/101-numpy-exercises-python/